apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80  ## Exposes the service on port 80.
    targetPort: 80 #Pod's container listens on 80, if you dont use this line, K8s will assign default 80 port.


