apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-fixed-count-job
spec:
  completions: 6
  parallelism: 3
  template:
    spec:
      containers:
      - name: parallel-fixed-count-container
        image: busybox
        command: ["echo", "Hello from the parallel-fixed-count job"]
      restartPolicy: Never
  