apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 80  
    targetPort: 80 # Ensure this matches the container's port, if you dont use this line, K8s will assign default 80 port.
    nodePort: 30007 # If you dont mention target and nodeports, K8s will generate random nodeport and target port 80.
